version: '3.7'
services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - 80:8083
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        user: user
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: 'laravelapp'
        volumes:
            - ./:/var/www/html
        user: user
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'laraapp_db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ""
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
